name: Deploy Ticket Service

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH and Deploy to EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USERNAME }}
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          script: |
            cd ${{ secrets.APP_PATH }}
            git pull origin main
            pip install -r requirements.txt
            pm2 describe ticket-service >/dev/null 2>&1 && pm2 restart ticket-service || pm2 start "uvicorn ticket_service:app --host 0.0.0.0 --port 8025" --name ticket-service
            pm2 save
